USE [master]
GO

/****** Object:  Database [DB_DISLOG]    Script Date: 09/11/2016 18:34:11 ******/
CREATE DATABASE [DB_DISLOG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_DISLOG', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DB_DISLOG.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DB_DISLOG_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DB_DISLOG_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DB_DISLOG] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_DISLOG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_DISLOG] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_DISLOG] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_DISLOG] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_DISLOG] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_DISLOG] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_DISLOG] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_DISLOG] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_DISLOG] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_DISLOG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_DISLOG] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_DISLOG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_DISLOG] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_DISLOG] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_DISLOG] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_DISLOG] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_DISLOG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_DISLOG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_DISLOG] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_DISLOG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_DISLOG] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_DISLOG] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_DISLOG] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_DISLOG] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_DISLOG] SET  MULTI_USER 
GO

ALTER DATABASE [DB_DISLOG] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_DISLOG] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_DISLOG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_DISLOG] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DB_DISLOG] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_DISLOG] SET  READ_WRITE 
GO

