USE [DB_DISLOG]
GO

/****** Object:  Table [dbo].[SEGURANCA.USUARIOS]    Script Date: 09/11/2016 18:35:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SEGURANCA.USUARIOS](
	[ID_USUARIO] [int] NOT NULL,
	[LOGIN_USUARIO] [varchar](100) NOT NULL,
	[EMAIL_USUARIO] [varchar](150) NOT NULL,
	[SENHA_USUARIO] [varbinary](100) NOT NULL,
	[ADM_USUARIO] [tinyint] NOT NULL,
	[EXPIRA_USUARIO] [tinyint] NOT NULL,
	[DIAS_USUARIO] [tinyint] NOT NULL,
	[DATA_SENHA_USUARIO] [date] NOT NULL,
	[ATIVO_USUARIO] [tinyint] NOT NULL,
	[LOG_USUARIO] [text] NOT NULL,
 CONSTRAINT [PK_SEGURANCA.USUARIOS] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

